Algoritmo "exemplo_menor_de_três"

Var
a, b, c : inteiro


Inicio

Escreval("Digite o primeiro número: ")

leia(a)

Escreval("Digite o segundo número: ")

leia(b)

Escreval("Digite o terceiro número: ")

leia (c)



Se (a <= b) e (a <= c) entao

   escreva( "MENOR = ", a)

   senao

     se  (b <= c) então

     escreva( "MENOR = ", b)

     senao

     escreva( "MENOR = ", c)



fimse



  fimse


Fimalgoritmo