Algoritmo "exemplo_idades"

Var

nome1, nome2 : caractere
idade1, idade2,  real


Inicio

escreval("Dados da primeira pessoa: ")
Escreval("Nome: ")
leia(nome1)
Escreval("Idade: ")
leia(idade1)
Escreval("Dados da segunda pessoa: ")
Escreval("Nome: ")
leia(nome2)
Escreval("Idade: ")
leia(idade2)

media <- (idade1+idade2)/2

Escreval("A idade média entre ", nome1 , " e " , nome2 , " é de", media:0:2, " anos.")

Fimalgoritmo